/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as ProfilesImport } from './routes/profiles'
import { Route as ProfileImport } from './routes/profile'
import { Route as LogoutImport } from './routes/logout'
import { Route as LoginImport } from './routes/login'
import { Route as ForgotPasswordImport } from './routes/forgot-password'
import { Route as IndexImport } from './routes/index'
import { Route as ContactIndexImport } from './routes/contact/index'
import { Route as BlogIndexImport } from './routes/blog/index'
import { Route as AboutIndexImport } from './routes/about/index'
import { Route as VerifyEmailEmailImport } from './routes/verify-email.$email'
import { Route as ShopLoginImport } from './routes/shop/login'
import { Route as ShopCheckoutImport } from './routes/shop/checkout'
import { Route as ShopAddCartImport } from './routes/shop/add-cart'
import { Route as ShopIndexCategoryidImport } from './routes/shop/index.$category_id'
import { Route as ShopOrderedSuccessOrderidImport } from './routes/shop/ordered-success.$order_id'
import { Route as BlogViewIdImport } from './routes/blog/view.$id'
import { Route as ShopViewProductIDCategoryIDImport } from './routes/shop/view.$productID.$categoryID'
import { Route as ShopBuyCheckoutCartidProductidImport } from './routes/shop/buy-checkout.$cart_id.$product_id'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const ProfilesRoute = ProfilesImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRoute,
} as any)

const ProfileRoute = ProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const LogoutRoute = LogoutImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ForgotPasswordRoute = ForgotPasswordImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContactIndexRoute = ContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

const BlogIndexRoute = BlogIndexImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRoute,
} as any)

const AboutIndexRoute = AboutIndexImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRoute,
} as any)

const VerifyEmailEmailRoute = VerifyEmailEmailImport.update({
  id: '/verify-email/$email',
  path: '/verify-email/$email',
  getParentRoute: () => rootRoute,
} as any)

const ShopLoginRoute = ShopLoginImport.update({
  id: '/shop/login',
  path: '/shop/login',
  getParentRoute: () => rootRoute,
} as any)

const ShopCheckoutRoute = ShopCheckoutImport.update({
  id: '/shop/checkout',
  path: '/shop/checkout',
  getParentRoute: () => rootRoute,
} as any)

const ShopAddCartRoute = ShopAddCartImport.update({
  id: '/shop/add-cart',
  path: '/shop/add-cart',
  getParentRoute: () => rootRoute,
} as any)

const ShopIndexCategoryidRoute = ShopIndexCategoryidImport.update({
  id: '/shop/index/$category_id',
  path: '/shop/index/$category_id',
  getParentRoute: () => rootRoute,
} as any)

const ShopOrderedSuccessOrderidRoute = ShopOrderedSuccessOrderidImport.update({
  id: '/shop/ordered-success/$order_id',
  path: '/shop/ordered-success/$order_id',
  getParentRoute: () => rootRoute,
} as any)

const BlogViewIdRoute = BlogViewIdImport.update({
  id: '/blog/view/$id',
  path: '/blog/view/$id',
  getParentRoute: () => rootRoute,
} as any)

const ShopViewProductIDCategoryIDRoute =
  ShopViewProductIDCategoryIDImport.update({
    id: '/shop/view/$productID/$categoryID',
    path: '/shop/view/$productID/$categoryID',
    getParentRoute: () => rootRoute,
  } as any)

const ShopBuyCheckoutCartidProductidRoute =
  ShopBuyCheckoutCartidProductidImport.update({
    id: '/shop/buy-checkout/$cart_id/$product_id',
    path: '/shop/buy-checkout/$cart_id/$product_id',
    getParentRoute: () => rootRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutImport
      parentRoute: typeof rootRoute
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileImport
      parentRoute: typeof rootRoute
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/shop/add-cart': {
      id: '/shop/add-cart'
      path: '/shop/add-cart'
      fullPath: '/shop/add-cart'
      preLoaderRoute: typeof ShopAddCartImport
      parentRoute: typeof rootRoute
    }
    '/shop/checkout': {
      id: '/shop/checkout'
      path: '/shop/checkout'
      fullPath: '/shop/checkout'
      preLoaderRoute: typeof ShopCheckoutImport
      parentRoute: typeof rootRoute
    }
    '/shop/login': {
      id: '/shop/login'
      path: '/shop/login'
      fullPath: '/shop/login'
      preLoaderRoute: typeof ShopLoginImport
      parentRoute: typeof rootRoute
    }
    '/verify-email/$email': {
      id: '/verify-email/$email'
      path: '/verify-email/$email'
      fullPath: '/verify-email/$email'
      preLoaderRoute: typeof VerifyEmailEmailImport
      parentRoute: typeof rootRoute
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutIndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogIndexImport
      parentRoute: typeof rootRoute
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexImport
      parentRoute: typeof rootRoute
    }
    '/blog/view/$id': {
      id: '/blog/view/$id'
      path: '/blog/view/$id'
      fullPath: '/blog/view/$id'
      preLoaderRoute: typeof BlogViewIdImport
      parentRoute: typeof rootRoute
    }
    '/shop/ordered-success/$order_id': {
      id: '/shop/ordered-success/$order_id'
      path: '/shop/ordered-success/$order_id'
      fullPath: '/shop/ordered-success/$order_id'
      preLoaderRoute: typeof ShopOrderedSuccessOrderidImport
      parentRoute: typeof rootRoute
    }
    '/shop/index/$category_id': {
      id: '/shop/index/$category_id'
      path: '/shop/index/$category_id'
      fullPath: '/shop/index/$category_id'
      preLoaderRoute: typeof ShopIndexCategoryidImport
      parentRoute: typeof rootRoute
    }
    '/shop/buy-checkout/$cart_id/$product_id': {
      id: '/shop/buy-checkout/$cart_id/$product_id'
      path: '/shop/buy-checkout/$cart_id/$product_id'
      fullPath: '/shop/buy-checkout/$cart_id/$product_id'
      preLoaderRoute: typeof ShopBuyCheckoutCartidProductidImport
      parentRoute: typeof rootRoute
    }
    '/shop/view/$productID/$categoryID': {
      id: '/shop/view/$productID/$categoryID'
      path: '/shop/view/$productID/$categoryID'
      fullPath: '/shop/view/$productID/$categoryID'
      preLoaderRoute: typeof ShopViewProductIDCategoryIDImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/shop/add-cart': typeof ShopAddCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/login': typeof ShopLoginRoute
  '/verify-email/$email': typeof VerifyEmailEmailRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/blog/view/$id': typeof BlogViewIdRoute
  '/shop/ordered-success/$order_id': typeof ShopOrderedSuccessOrderidRoute
  '/shop/index/$category_id': typeof ShopIndexCategoryidRoute
  '/shop/buy-checkout/$cart_id/$product_id': typeof ShopBuyCheckoutCartidProductidRoute
  '/shop/view/$productID/$categoryID': typeof ShopViewProductIDCategoryIDRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/shop/add-cart': typeof ShopAddCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/login': typeof ShopLoginRoute
  '/verify-email/$email': typeof VerifyEmailEmailRoute
  '/about': typeof AboutIndexRoute
  '/blog': typeof BlogIndexRoute
  '/contact': typeof ContactIndexRoute
  '/blog/view/$id': typeof BlogViewIdRoute
  '/shop/ordered-success/$order_id': typeof ShopOrderedSuccessOrderidRoute
  '/shop/index/$category_id': typeof ShopIndexCategoryidRoute
  '/shop/buy-checkout/$cart_id/$product_id': typeof ShopBuyCheckoutCartidProductidRoute
  '/shop/view/$productID/$categoryID': typeof ShopViewProductIDCategoryIDRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/logout': typeof LogoutRoute
  '/profile': typeof ProfileRoute
  '/profiles': typeof ProfilesRoute
  '/signup': typeof SignupRoute
  '/shop/add-cart': typeof ShopAddCartRoute
  '/shop/checkout': typeof ShopCheckoutRoute
  '/shop/login': typeof ShopLoginRoute
  '/verify-email/$email': typeof VerifyEmailEmailRoute
  '/about/': typeof AboutIndexRoute
  '/blog/': typeof BlogIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/blog/view/$id': typeof BlogViewIdRoute
  '/shop/ordered-success/$order_id': typeof ShopOrderedSuccessOrderidRoute
  '/shop/index/$category_id': typeof ShopIndexCategoryidRoute
  '/shop/buy-checkout/$cart_id/$product_id': typeof ShopBuyCheckoutCartidProductidRoute
  '/shop/view/$productID/$categoryID': typeof ShopViewProductIDCategoryIDRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/profile'
    | '/profiles'
    | '/signup'
    | '/shop/add-cart'
    | '/shop/checkout'
    | '/shop/login'
    | '/verify-email/$email'
    | '/about'
    | '/blog'
    | '/contact'
    | '/blog/view/$id'
    | '/shop/ordered-success/$order_id'
    | '/shop/index/$category_id'
    | '/shop/buy-checkout/$cart_id/$product_id'
    | '/shop/view/$productID/$categoryID'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/profile'
    | '/profiles'
    | '/signup'
    | '/shop/add-cart'
    | '/shop/checkout'
    | '/shop/login'
    | '/verify-email/$email'
    | '/about'
    | '/blog'
    | '/contact'
    | '/blog/view/$id'
    | '/shop/ordered-success/$order_id'
    | '/shop/index/$category_id'
    | '/shop/buy-checkout/$cart_id/$product_id'
    | '/shop/view/$productID/$categoryID'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/logout'
    | '/profile'
    | '/profiles'
    | '/signup'
    | '/shop/add-cart'
    | '/shop/checkout'
    | '/shop/login'
    | '/verify-email/$email'
    | '/about/'
    | '/blog/'
    | '/contact/'
    | '/blog/view/$id'
    | '/shop/ordered-success/$order_id'
    | '/shop/index/$category_id'
    | '/shop/buy-checkout/$cart_id/$product_id'
    | '/shop/view/$productID/$categoryID'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  LogoutRoute: typeof LogoutRoute
  ProfileRoute: typeof ProfileRoute
  ProfilesRoute: typeof ProfilesRoute
  SignupRoute: typeof SignupRoute
  ShopAddCartRoute: typeof ShopAddCartRoute
  ShopCheckoutRoute: typeof ShopCheckoutRoute
  ShopLoginRoute: typeof ShopLoginRoute
  VerifyEmailEmailRoute: typeof VerifyEmailEmailRoute
  AboutIndexRoute: typeof AboutIndexRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
  BlogViewIdRoute: typeof BlogViewIdRoute
  ShopOrderedSuccessOrderidRoute: typeof ShopOrderedSuccessOrderidRoute
  ShopIndexCategoryidRoute: typeof ShopIndexCategoryidRoute
  ShopBuyCheckoutCartidProductidRoute: typeof ShopBuyCheckoutCartidProductidRoute
  ShopViewProductIDCategoryIDRoute: typeof ShopViewProductIDCategoryIDRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  LogoutRoute: LogoutRoute,
  ProfileRoute: ProfileRoute,
  ProfilesRoute: ProfilesRoute,
  SignupRoute: SignupRoute,
  ShopAddCartRoute: ShopAddCartRoute,
  ShopCheckoutRoute: ShopCheckoutRoute,
  ShopLoginRoute: ShopLoginRoute,
  VerifyEmailEmailRoute: VerifyEmailEmailRoute,
  AboutIndexRoute: AboutIndexRoute,
  BlogIndexRoute: BlogIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
  BlogViewIdRoute: BlogViewIdRoute,
  ShopOrderedSuccessOrderidRoute: ShopOrderedSuccessOrderidRoute,
  ShopIndexCategoryidRoute: ShopIndexCategoryidRoute,
  ShopBuyCheckoutCartidProductidRoute: ShopBuyCheckoutCartidProductidRoute,
  ShopViewProductIDCategoryIDRoute: ShopViewProductIDCategoryIDRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/forgot-password",
        "/login",
        "/logout",
        "/profile",
        "/profiles",
        "/signup",
        "/shop/add-cart",
        "/shop/checkout",
        "/shop/login",
        "/verify-email/$email",
        "/about/",
        "/blog/",
        "/contact/",
        "/blog/view/$id",
        "/shop/ordered-success/$order_id",
        "/shop/index/$category_id",
        "/shop/buy-checkout/$cart_id/$product_id",
        "/shop/view/$productID/$categoryID"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/forgot-password": {
      "filePath": "forgot-password.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/logout": {
      "filePath": "logout.tsx"
    },
    "/profile": {
      "filePath": "profile.tsx"
    },
    "/profiles": {
      "filePath": "profiles.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/shop/add-cart": {
      "filePath": "shop/add-cart.tsx"
    },
    "/shop/checkout": {
      "filePath": "shop/checkout.tsx"
    },
    "/shop/login": {
      "filePath": "shop/login.tsx"
    },
    "/verify-email/$email": {
      "filePath": "verify-email.$email.tsx"
    },
    "/about/": {
      "filePath": "about/index.tsx"
    },
    "/blog/": {
      "filePath": "blog/index.tsx"
    },
    "/contact/": {
      "filePath": "contact/index.tsx"
    },
    "/blog/view/$id": {
      "filePath": "blog/view.$id.tsx"
    },
    "/shop/ordered-success/$order_id": {
      "filePath": "shop/ordered-success.$order_id.tsx"
    },
    "/shop/index/$category_id": {
      "filePath": "shop/index.$category_id.tsx"
    },
    "/shop/buy-checkout/$cart_id/$product_id": {
      "filePath": "shop/buy-checkout.$cart_id.$product_id.tsx"
    },
    "/shop/view/$productID/$categoryID": {
      "filePath": "shop/view.$productID.$categoryID.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
